//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyCauThu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("quanLyCauThu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1031497 {
            get {
                object obj = ResourceManager.GetObject("1031497", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1781535_200 {
            get {
                object obj = ResourceManager.GetObject("1781535-200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _233723800_10158411442202616_5974656413147135446_n {
            get {
                object obj = ResourceManager.GetObject("233723800_10158411442202616_5974656413147135446_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _435261359_793154676019168_7077615438791971204_n {
            get {
                object obj = ResourceManager.GetObject("435261359_793154676019168_7077615438791971204_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5525464 {
            get {
                object obj = ResourceManager.GetObject("5525464", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8079129 {
            get {
                object obj = ResourceManager.GetObject("8079129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dbb598b3e1fa7ed282fd0390e45cdc58 {
            get {
                object obj = ResourceManager.GetObject("dbb598b3e1fa7ed282fd0390e45cdc58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Football_Manager_2024 {
            get {
                object obj = ResourceManager.GetObject("Football-Manager-2024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Football_Manager_2024_Logo {
            get {
                object obj = ResourceManager.GetObject("Football_Manager_2024_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goal_icon_ball_football_icon_design_sports_symbol_association_football_referee_soccer_ball_png_clipart_thumbnail {
            get {
                object obj = ResourceManager.GetObject("goal-icon-ball-football-icon-design-sports-symbol-association-football-referee-so" +
                        "ccer-ball-png-clipart-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_636394506_1024x1024 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-636394506-1024x1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_970489978_1024x1024 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-970489978-1024x1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_football_manager_2014_football_manager_2016_footba_manager_5ac2eea7e26551_7650880215227245199273 {
            get {
                object obj = ResourceManager.GetObject("kisspng-football-manager-2014-football-manager-2016-footba-manager-5ac2eea7e26551" +
                        ".7650880215227245199273", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_calendar_time_icon_calendar_holidays_text {
            get {
                object obj = ResourceManager.GetObject("png-clipart-calendar-time-icon-calendar-holidays-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_cristiano_ronaldo_illustration_fifa_18_2014_fifa_world_cup_real_madrid_c_f_portugal_national_football_team_la_liga_cristiano_ronaldo_sports_equipment_jersey_sp__1_ {
            get {
                object obj = ResourceManager.GetObject("png-transparent-cristiano-ronaldo-illustration-fifa-18-2014-fifa-world-cup-real-m" +
                        "adrid-c-f-portugal-national-football-team-la-liga-cristiano-ronaldo-sports-equip" +
                        "ment-jersey-sp (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_cristiano_ronaldo_illustration_fifa_18_2014_fifa_world_cup_real_madrid_c_f_portugal_national_football_team_la_liga_cristiano_ronaldo_sports_equipment_jersey_sports {
            get {
                object obj = ResourceManager.GetObject("png-transparent-cristiano-ronaldo-illustration-fifa-18-2014-fifa-world-cup-real-m" +
                        "adrid-c-f-portugal-national-football-team-la-liga-cristiano-ronaldo-sports-equip" +
                        "ment-jersey-sports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap silhouette_soccer_player_vector_illustration_linocut_969863_303468 {
            get {
                object obj = ResourceManager.GetObject("silhouette-soccer-player-vector-illustration-linocut_969863-303468", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z5945270707947_1450df2441fb30e19cdd75848f1d81d5 {
            get {
                object obj = ResourceManager.GetObject("z5945270707947_1450df2441fb30e19cdd75848f1d81d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
